"""Best-effort CloudFormation generator for deployable recommendations.

Goal: provide an IaC artifact customers can deploy directly.
Scope (MVP): generate a minimal but valid stack for common web-app patterns:
- VPC + 2 public + 2 private subnets
- SecurityGroups
- (optional) ALB + TargetGroup + Listener
- (optional) EC2 AutoScalingGroup (or single EC2 instance)
- (optional) RDS DBInstance + DBSubnetGroup
- (optional) S3 Bucket

If recommended services don't map cleanly, we still output a safe minimal VPC stack
plus placeholders via Parameters/Outputs.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional, Tuple

from ...models.architecture_recommendation import ArchitectureRecommendation


def _svc_present(services_by_name: Dict[str, int], *names: str) -> bool:
    for n in names:
        if services_by_name.get(n.lower(), 0) > 0:
            return True
    return False


def _cfg_value(rec: ArchitectureRecommendation, *, key: str, fallback: str) -> str:
    """Find the first config_value with matching config_type."""
    k = (key or "").strip().lower()
    for c in rec.configurations or []:
        if (c.config_type or "").strip().lower() == k and (c.config_value or "").strip():
            return str(c.config_value).strip()
    return fallback


@dataclass(frozen=True)
class CloudFormationBuildResult:
    template_yaml: str
    notes: Tuple[str, ...] = ()


class CloudFormationGenerator:
    """Generate a CloudFormation template YAML from a recommendation."""

    def generate(self, recommendation: ArchitectureRecommendation) -> CloudFormationBuildResult:
        services_by_name = {}
        for s in recommendation.services or []:
            services_by_name[(s.aws_service_name or "").strip().lower()] = services_by_name.get(
                (s.aws_service_name or "").strip().lower(), 0
            ) + 1

        want_ec2 = _svc_present(services_by_name, "ec2", "amazon ec2")
        want_rds = _svc_present(services_by_name, "rds", "amazon rds")
        want_s3 = _svc_present(services_by_name, "s3", "amazon s3")
        want_alb = _svc_present(
            services_by_name,
            "alb",
            "application load balancer",
            "elastic load balancing",
            "elbv2",
        )

        # Heuristic: if EC2 quantity > 1, assume AutoScalingGroup
        ec2_qty = 1
        if want_ec2:
            for s in recommendation.services or []:
                if (s.aws_service_name or "").strip().lower() in {"ec2", "amazon ec2"}:
                    ec2_qty = max(int(getattr(s, "quantity", 1) or 1), 1)
                    break
        want_asg = want_ec2 and (ec2_qty > 1 or want_alb)

        instance_type = _cfg_value(recommendation, key="instance_type", fallback="t3.micro")
        db_instance_class = _cfg_value(recommendation, key="db_instance_class", fallback="db.t3.micro")
        db_allocated_storage = _cfg_value(recommendation, key="storage_size", fallback="20")

        # Build YAML (long-form intrinsics only, to keep PyYAML parsing simple and portable).
        # Note: this is intentionally conservative to avoid unsupported shorthand tags (!Ref, !Sub).
        notes = []
        if want_rds and not want_ec2:
            notes.append("检测到 RDS 但未检测到 EC2：模板仍会创建基础网络与 RDS。")
        if not (want_ec2 or want_rds or want_s3 or want_alb):
            notes.append("未识别到可映射的核心服务：模板输出基础网络骨架（可在此基础上扩展）。")

        desc = "Generated by aws-arch-agent (deployable CloudFormation, best-effort)."

        yaml = f"""AWSTemplateFormatVersion: "2010-09-09"
Description: "{desc}"

Parameters:
  VpcCidr:
    Type: String
    Default: "10.0.0.0/16"
  PublicSubnet1Cidr:
    Type: String
    Default: "10.0.0.0/24"
  PublicSubnet2Cidr:
    Type: String
    Default: "10.0.1.0/24"
  PrivateSubnet1Cidr:
    Type: String
    Default: "10.0.10.0/24"
  PrivateSubnet2Cidr:
    Type: String
    Default: "10.0.11.0/24"
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
  InstanceType:
    Type: String
    Default: "{instance_type}"
  DbInstanceClass:
    Type: String
    Default: "{db_instance_class}"
  DbAllocatedStorage:
    Type: Number
    Default: {int(str(db_allocated_storage).strip() or "20")}
  DbUsername:
    Type: String
    Default: "appuser"
  DbPassword:
    Type: String
    NoEcho: true
    Default: "ChangeMe123!"

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: PublicSubnet1Cidr
      MapPublicIpOnLaunch: true
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: PublicSubnet2Cidr
      MapPublicIpOnLaunch: true
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: PrivateSubnet1Cidr
      MapPublicIpOnLaunch: false
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: PrivateSubnet2Cidr
      MapPublicIpOnLaunch: false
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId:
        Ref: InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PublicSubnet1
      RouteTableId:
        Ref: PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PublicSubnet2
      RouteTableId:
        Ref: PublicRouteTable

  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "ALB security group"
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"

  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "App instances security group"
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId:
            Ref: AlbSecurityGroup
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"

  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Database security group"
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId:
            Ref: AppSecurityGroup
"""

        if want_s3:
            yaml += """
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
"""

        if want_alb:
            yaml += """
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
        - Ref: PublicSubnet1
        - Ref: PublicSubnet2
      SecurityGroups:
        - Ref: AlbSecurityGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId:
        Ref: VPC
      Protocol: HTTP
      Port: 80
      TargetType: instance
      HealthCheckPath: "/"

  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn:
        Ref: LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: TargetGroup
"""

        if want_ec2 and want_asg:
            yaml += f"""
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId:
          Ref: LatestAmiId
        InstanceType:
          Ref: InstanceType
        SecurityGroupIds:
          - Ref: AppSecurityGroup
        UserData:
          Fn::Base64:
            Fn::Sub: |
              #!/bin/bash
              set -e
              dnf update -y
              dnf install -y nginx
              systemctl enable nginx
              echo "hello from aws-arch-agent" > /usr/share/nginx/html/index.html
              systemctl start nginx

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - Ref: PublicSubnet1
        - Ref: PublicSubnet2
      MinSize: "{max(1, min(ec2_qty, 2))}"
      MaxSize: "{max(ec2_qty, 2)}"
      DesiredCapacity: "{ec2_qty}"
      LaunchTemplate:
        LaunchTemplateId:
          Ref: LaunchTemplate
        Version:
          Fn::GetAtt:
            - LaunchTemplate
            - LatestVersionNumber
"""
            if want_alb:
                yaml += """
      TargetGroupARNs:
        - Ref: TargetGroup
"""

        elif want_ec2:
            # single EC2 instance (public subnet)
            yaml += """
  AppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: LatestAmiId
      InstanceType:
        Ref: InstanceType
      SubnetId:
        Ref: PublicSubnet1
      SecurityGroupIds:
        - Ref: AppSecurityGroup
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #!/bin/bash
            set -e
            dnf update -y
            dnf install -y nginx
            systemctl enable nginx
            echo "hello from aws-arch-agent" > /usr/share/nginx/html/index.html
            systemctl start nginx
"""

        if want_rds:
            yaml += """
  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "DB subnets"
      SubnetIds:
        - Ref: PrivateSubnet1
        - Ref: PrivateSubnet2

  DbInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: mysql
      DBInstanceClass:
        Ref: DbInstanceClass
      AllocatedStorage:
        Ref: DbAllocatedStorage
      MasterUsername:
        Ref: DbUsername
      MasterUserPassword:
        Ref: DbPassword
      VPCSecurityGroups:
        - Ref: DbSecurityGroup
      DBSubnetGroupName:
        Ref: DbSubnetGroup
      PubliclyAccessible: false
      BackupRetentionPeriod: 7
      MultiAZ: true
"""

        yaml += """

Outputs:
  VpcId:
    Value:
      Ref: VPC
"""
        if want_alb:
            yaml += """
  AlbDnsName:
    Value:
      Fn::GetAtt:
        - LoadBalancer
        - DNSName
"""
        if want_ec2 and not want_asg and not want_alb:
            yaml += """
  AppPublicIp:
    Value:
      Fn::GetAtt:
        - AppInstance
        - PublicIp
"""
        if want_rds:
            yaml += """
  DbEndpoint:
    Value:
      Fn::GetAtt:
        - DbInstance
        - Endpoint.Address
"""
        if want_s3:
            yaml += """
  BucketName:
    Value:
      Ref: AppBucket
"""

        return CloudFormationBuildResult(template_yaml=yaml.strip() + "\n", notes=tuple(notes))

